### ISSUE TITLE
parameter secret causes YAML parsing error.

### ISSUE THREAD

**Issue by marxjohnson** [MicrosoftDocs/azure-devops-docs#9111]
Following the documentation, I have tried to create a secret parameter in my pipeline, like this:
```
parameters:
  - name: Dbpass
    displayName: Database password
    type: string
    secret: true
```
However, when I try to run the pipeline, I get the following error:
```
Encountered error(s) while parsing pipeline YAML:
azure-pipelines.yaml (Line: 22, Col: 5): Unexpected value 'secret'
```

Am I doing something wrong, or is the documention incorrect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#parameters)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@marxjohnson Thank you for the feedback.

Unfortunately the `secret` designation appears to be unsupported, see [here](https://developercommunity.visualstudio.com/content/problem/1035297/unable-to-define-secret-run-time-parameters.html).

Assigning this to the author for review of the documentation.

**Comment by steved0x** [comment]
@marxjohnson That is an error in our documentation that I just fixed and it should be live soon. I'm not sure how that got there, and I am sorry that it caused you trouble. Thank you for letting us know.

**Comment by victorsarmi** [comment]
documentation still have the error
https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/runtime-parameters.md

**Comment by WilliamAntonRohm** [comment]
@victorsarmi -- Victor, thank you for your follow-up.  The article you mention states:
> Status: implemented, with some changes from the below information. See [the official documentation](https://docs.microsoft.com/azure/devops/pipelines/process/runtime-parameters) for latest information.

and the referenced documentation is up-to-date.
