### ISSUE TITLE
Does System.StageAttempt really increment when the job is retried?

### ISSUE THREAD

**Issue by dagood** [MicrosoftDocs/azure-devops-docs#9309]
I assume this is a typo:

> Set to 1 the first time this **stage** is attempted, and increments every time the **job** is retried.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@dagood  Thank you for the feedback.

Yes, this is the documented behavior.  Are there instances where this is not incrementing?  

For product-related issues, please move this to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit additional feedback.

A similar post can be found [here](https://developercommunity.visualstudio.com/content/problem/1093182/systemstageattempt-set-to-incorrect-value-on-serve.html).

**Comment by dagood** [comment]
Hmm. I thought it would simply be a typo, where "the job" was meant to be "this stage".

I'm lost what this line means, then, so I can't say whether there's a behavior mismatch. 😕 If `StageAttempt` is intended to increment every time "the job" is retried, what is "the job"?

**Comment by msebolt** [comment]
Perhaps, though `System.PhaseAttempt` is also seemingly tied to only the job rerunning.

Assigning this to the author for further review.

**Comment by dagood** [comment]
Yeah, `PhaseAttempt` appears to have a similar typo and is similarly incomprehensible to me if it's not a typo. 😛

**Comment by juliakm** [comment]
Looks like this has been fixed. See https://developercommunity.visualstudio.com/content/problem/1093182/systemstageattempt-set-to-incorrect-value-on-serve.html.

**Comment by dagood** [comment]
That bug looks unrelated to me. The (presumed) doc bug is still in the docs.
